info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    device:
      path: /device/**
    vision:
      path: /vision/**


server:
  port: 1234
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/


