# Configure this Discovery Server
eureka:
  instance:
    hostname: 127.0.0.1
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    eurekaServerPort: 1111
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    
server:
  port: 1111